### PR TITLE
XRP Support

### PR DESCRIPTION
**Pull request by mattiavarile**
This modification enables XRP support

### CODE REVIEW

**Comment by brndnmtthws** [comment]
Thanks for the PR. A few questions:

- can we pull the precision values from the CB API? I assume the data is in there somewhere
- perhaps you can add some XRP specific tests?
- we shouldn't break the existing tests

**Comment by mattiavarile** [comment]
Hi Brenden,

unfortunately, I'm not sure what do mean with 'precision values', following coinbase API docs:

> Money values are represented by a hash object which contains amount and currency fields. The amount is always returned as a string which you should be careful when parsing to have correct decimal precision. Bitcoin, Bitcoin Cash, Litecoin and Ethereum values will have 8 decimal points and fiat currencies will have two.

but I think it also extends also to XRP.

On your second point, unfortunately, I'm not an expert on testing the code using Travis.

I will briefly explain the problems I tried to solve:

1. because of the price of XRP, lower than the unit, is necessary to fill orders using integer values (e.g.: 10 units NOT 10.054 units). I solved the issue inserting an `if/else `condition, specifically for XRP. However, this solution does not generalize well.

2. On the code there is  a particular `math.floor()` on `generate_buy_orders` function, which lead to lose two precision points (0.xx instead of 0.xxxx) on XRP price, lowering order fills resolution.

My solutions are not perfect but seems to work, for now. However, I hope you will implement an improved code based on my feedbacks

**Comment by brndnmtthws** [comment]
If I understand your PR correctly, the XRP order sizes are quite different, which is why your changes are required. The CB API provides some information about order size precision from the `/products` endpoint: https://docs.pro.coinbase.com/#products

Rather than hard coding the precision, we could simply use the fields from `/products`:

> The base_min_size and base_max_size fields define the min and max order size. The quote_increment field specifies the min order price as well as the price increment.

Does that make sense?

**Comment by mattiavarile** [comment]
That's right. Your solution would be even better, because generalize well.

**Comment by brndnmtthws** [comment]
Closing this due to inactivity.

**Pull request closed without merging**
